### ISSUE TITLE
Problem with Participate

### ISSUE THREAD

**Issue by ghost** [CodeColors/ConvoyManager#1]
![Screenshot_3](https://user-images.githubusercontent.com/60478593/73466658-7d95cc00-4382-11ea-867e-60268702c8f1.png)
![Screenshot_4](https://user-images.githubusercontent.com/60478593/73466719-92725f80-4382-11ea-8a9a-e21256564914.png)

**Comment by CodeColors** [comment]
Thank's for reporting this issue ! I will update the project soon.

**Comment by ghost** [comment]
thanks

**Comment by ghost** [comment]
Do you have fixed this?

**Comment by CodeColors** [comment]
Done !
